- src/main/java/mdteam/ait/AITMod.java
- src/main/java/mdteam/ait/client/AITModClient.java
- src/main/java/mdteam/ait/client/renderers/consoles/ConsoleRenderer.java
- src/main/java/mdteam/ait/core/AITConsoleVariants.java
- src/main/java/mdteam/ait/core/blockentities/ConsoleBlockEntity.java
- src/main/java/mdteam/ait/tardis/variant/AutumnVariant.java
- src/main/java/mdteam/ait/tardis/variant/BorealisVariant.java
- src/main/java/mdteam/ait/tardis/variant/ConsoleVariantSchema.java
- src/main/java/mdteam/ait/tardis/variant/HartnellVariant.java
- src/main/java/mdteam/ait/tardis/variant/TempVariant.java
is good consle variatn systme
thoguht it would take longer but noep
im going to rewrite exterior variant systemto be ike this
use repeating cmd blokc to change variant
> console variants be like

- src/main/java/mdteam/ait/client/models/exteriors/ExteriorModel.java
- src/main/java/mdteam/ait/core/blockentities/ExteriorBlockEntity.java
- src/main/java/mdteam/ait/core/util/AITConfigModel.java
- src/main/java/mdteam/ait/tardis/TardisExterior.java
- src/main/java/mdteam/ait/tardis/TardisManager.java
- src/main/java/mdteam/ait/tardis/TardisTravel.java
- src/main/java/mdteam/ait/tardis/control/impl/AutoPilotControl.java
- src/main/java/mdteam/ait/tardis/control/impl/TelepathicControl.java
- src/main/java/mdteam/ait/tardis/control/impl/pos/IncrementControl.java
- src/main/java/mdteam/ait/tardis/control/impl/pos/PosControl.java
- src/main/java/mdteam/ait/tardis/data/FuelData.java
- src/main/java/mdteam/ait/tardis/data/ServerAlarmHandler.java
- src/main/java/mdteam/ait/tardis/data/SiegeData.java
- src/main/java/mdteam/ait/tardis/link/LinkableBlockEntity.java
- src/main/java/mdteam/ait/tardis/wrapper/server/manager/ServerTardisManager.java
- src/main/resources/assets/ait/lang/en_us.existing.json
#192
#191
#190
#189 - ".old" file
#186
#183
#176
> update sync system + bug fixes idk why i made a seperate branch thought i was gna do more

- docs/_posts/2024-1-31-TARDIS-Protocals.md
- docs/_posts/2024-1-31-TARDIS-Protocols.md
> TARDIS-Protocals.md

- docs/_posts/2024-1-31-TARDIS-Protocols.md
> Updated the TARDIS protocol webpage to be more clear and add important information

- docs/_posts/2024-03-09-sonic.md
This is an update to the Sonic WIKI Page. and I have tried my best to make it great! :D 👍
> Update 2024-02-02-sonic.md to and improved 2024-03-09-sonic.md

- build.gradle
- src/main/java/loqor/ait/api/tardis/LinkableItem.java
- src/main/java/loqor/ait/client/AITModClient.java
- src/main/java/loqor/ait/client/util/ClientTardisUtil.java
- src/main/java/loqor/ait/core/item/KeyItem.java
- src/main/java/loqor/ait/tardis/control/impl/SecurityControl.java
- src/main/java/loqor/ait/tardis/data/TardisHandlersManager.java
- src/main/java/loqor/ait/tardis/data/loyalty/Loyalty.java
- src/main/java/loqor/ait/tardis/data/loyalty/LoyaltyData.java
- src/main/java/loqor/ait/tardis/data/loyalty/LoyaltyHandler.java
- src/main/java/loqor/ait/tardis/util/TardisUtil.java
- src/test/java/FaultySupplier.java
- src/test/java/LoyaltyTest.java
> loyalty, not finished though

- src/main/java/loqor/ait/datagen/AITModDataGenerator.java
- src/main/java/loqor/ait/tardis/data/InteriorChangingHandler.java
- src/main/java/loqor/ait/tardis/util/TardisUtil.java
inform link holders of regrowth completion
> enhancement #285

- src/main/java/loqor/ait/core/blockentities/DoorBlockEntity.java
- src/main/java/loqor/ait/core/blocks/DoorBlock.java
- src/main/java/loqor/ait/tardis/door/PoliceBoxDoorVariant.java
> fix some IP issues

- src/main/java/loqor/ait/core/dimension/sky/MarsSkyProperties.java
- src/main/java/loqor/ait/core/planet/Planet.java
- src/main/java/loqor/ait/core/planet/PlanetRegistry.java
- src/main/java/loqor/ait/core/util/PlanetInformation.java
- src/main/java/loqor/ait/mixin/server/gravity/AssortedEntityMixin.java
- src/main/java/loqor/ait/mixin/server/gravity/BoatEntityMixin.java
- src/main/java/loqor/ait/mixin/server/gravity/LivingEntityMixin.java
- src/main/java/loqor/ait/registry/Registries.java
> planet backend

- src/main/java/loqor/ait/core/config/AITConfigModel.java
- src/main/java/loqor/ait/core/lock/LockedDimension.java
- src/main/java/loqor/ait/core/lock/LockedDimensionRegistry.java
- src/main/java/loqor/ait/core/tardis/control/impl/DimensionControl.java
- src/main/java/loqor/ait/core/tardis/control/impl/TelepathicControl.java
- src/main/java/loqor/ait/core/tardis/handler/travel/TravelHandler.java
- src/main/java/loqor/ait/registry/Registries.java
- src/main/java/loqor/ait/registry/unlockable/Unlockable.java
#305 
datapacks can lock a dimension by defining an item needed to unlock it
unlocked by using the telepathic circuit while holding the item
this feature is togglable in the config
> Lockable Dimensions

- src/main/java/loqor/ait/core/blockentities/ExteriorBlockEntity.java
- src/main/java/loqor/ait/core/entities/FallingTardisEntity.java
- src/main/java/loqor/ait/core/lock/LockedDimensionRegistry.java
https://github.com/pavatus/ait/issues/425
https://github.com/pavatus/ait/issues/432
https://github.com/pavatus/ait/issues/417
> Minor Changes/Fixes

- src/main/java/loqor/ait/client/renderers/SonicRendering.java
> Fixed the one block offset in the z axis when rendering the marker for summoning the TARDIS

- src/main/java/dev/pavatus/planet/mixin/gravity/LivingEntityMixin.java
- src/main/java/loqor/ait/core/AITBlockEntityTypes.java
- src/main/java/loqor/ait/core/AITBlocks.java
- src/main/java/loqor/ait/core/AITItems.java
- src/main/java/loqor/ait/core/blockentities/LifeSupportBlockEntity.java
- src/main/java/loqor/ait/core/blocks/LifeSupportBlock.java
- src/main/java/loqor/ait/core/engine/SubSystem.java
- src/main/java/loqor/ait/core/engine/impl/LifeSupportCircuit.java
- src/main/java/loqor/ait/core/engine/impl/ShieldsCircuit.java
- src/main/java/loqor/ait/core/tardis/handler/ShieldHandler.java
- src/main/java/loqor/ait/core/tardis/handler/SiegeHandler.java
- src/main/java/loqor/ait/core/tardis/handler/SubSystemHandler.java
Life support should only be a block that connects up to the engine
the shields need a different structure, but Saturn hasn't given it to me yet.
> Life Support and Shields Subsystems

- src/main/java/dev/pavatus/register/datapack/DatapackRegistry.java
- src/main/java/loqor/ait/client/AITModClient.java
- src/main/java/loqor/ait/client/boti/BOTI.java
- src/main/java/loqor/ait/client/screens/interior/InteriorSettingsScreen.java
- src/main/java/loqor/ait/client/screens/widget/SwitcherManager.java
- src/main/java/loqor/ait/client/sounds/flight/ClientFlightHandler.java
- src/main/java/loqor/ait/client/sounds/flight/InteriorFlightSound.java
- src/main/java/loqor/ait/core/sounds/flight/FlightSound.java
- src/main/java/loqor/ait/core/sounds/flight/FlightSoundRegistry.java
- src/main/java/loqor/ait/core/sounds/travel/TravelSound.java
- src/main/java/loqor/ait/core/tardis/animation/ExteriorAnimation.java
- src/main/java/loqor/ait/core/tardis/animation/PulsatingAnimation.java
- src/main/java/loqor/ait/core/tardis/handler/StatsHandler.java
- src/main/java/loqor/ait/core/tardis/handler/travel/AnimatedTravelHandler.java
- src/main/java/loqor/ait/core/tardis/handler/travel/TravelHandler.java
- src/main/java/loqor/ait/core/tardis/vortex/reference/VortexReference.java
- src/main/java/loqor/ait/core/util/Cachable.java
- src/main/java/loqor/ait/data/datapack/DatapackExterior.java
- src/main/java/loqor/ait/data/hum/Hum.java
- src/main/java/loqor/ait/data/properties/Value.java
- src/main/java/loqor/ait/data/schema/exterior/ExteriorVariantSchema.java
- src/main/java/loqor/ait/registry/impl/exterior/ExteriorVariantRegistry.java
api: fx are no longer exterior defined
> selection screen for fx

- src/main/java/dev/amble/ait/core/tardis/control/impl/ElectricalDischargeControl.java
- src/main/java/dev/amble/ait/data/schema/console/type/AlnicoType.java
- src/main/java/dev/amble/ait/data/schema/console/type/CopperType.java
- src/main/java/dev/amble/ait/data/schema/console/type/CoralType.java
- src/main/java/dev/amble/ait/data/schema/console/type/CrystallineType.java
- src/main/java/dev/amble/ait/data/schema/console/type/HartnellType.java
- src/main/java/dev/amble/ait/data/schema/console/type/HourglassType.java
- src/main/java/dev/amble/ait/data/schema/console/type/HudolinType.java
- src/main/java/dev/amble/ait/data/schema/console/type/RenaissanceType.java
- src/main/java/dev/amble/ait/data/schema/console/type/SteamType.java
- src/main/java/dev/amble/ait/data/schema/console/type/ToyotaType.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
- src/main/java/dev/amble/ait/registry/impl/ControlRegistry.java
adds the electric discharge control
needs optimizing really really badly
> Electrical Discharge Control

- src/main/java/dev/amble/ait/core/item/TardisItemBuilder.java
- src/main/java/dev/amble/ait/core/item/sonic/ScanningSonicMode.java
- src/main/java/dev/amble/ait/core/item/sonic/SonicMode.java
- src/main/java/dev/amble/ait/core/item/sonic/TardisSonicMode.java
Hold in Main Hand to summon to target block
Hold in Off Hand for other features
- Look up to Send to Flight
- Look down to refuel
closes #869
> feat: TARDIS Sonic Mode

- src/main/java/dev/amble/ait/core/item/TardisItemBuilder.java
- src/main/java/dev/amble/ait/core/tardis/handler/LoyaltyHandler.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
@MaketendoDev 
Use this as an example of what to do *instead* of `.append`
> Fix Loyalty Messages

- src/main/java/dev/amble/ait/client/renderers/exteriors/ExteriorRenderer.java
i ayent typin allthat
anyway so disc now enables party mode ok cool
> party mode disc

- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
> this is silly

- README.md
my credit link
so people are directed to a general place for my stuff
> my credit is now my website :D

- .github/workflows/pr-labeler-approve.yml
- .github/workflows/pr-labeler-conflict.yml
- .github/workflows/pr-labeler-create.yml
- .github/workflows/pr-labeler-review.yml
- .github/workflows/pr-labeler-stable.yml
- .github/workflows/pr-labeler-staging.yml
- .github/workflows/pr-labeler.yml
Updates the workflows. Just some formatting, nothing crazy.
**Changelog**
> ci: update workflows

- src/main/java/dev/amble/ait/core/blockentities/EnvironmentProjectorBlockEntity.java
just formats the environment projector class
> fmt: EnvironmentProjectorBlockEntity

- .github/workflows/publish-devbuilds.yml
Build any branch & send it to beta testers.
Since the workflow already filters for changed code files, why not just remove the condition for branches?
> ci: build any branch if it has some code changed

- src/main/java/dev/amble/ait/core/blocks/MatrixEnergizerBlock.java
- src/main/java/dev/amble/ait/core/item/PersonalityMatrixItem.java
> fix: matrix energizer

- src/main/resources/data/ait/exterior/bt.json
Fixes the bt exterior json schema.
> fix: the bt exterior should use proper json

- src/main/resources/data/ait/exterior/geometric_green.json
Like the previous PR but for geometric green
> fix: geometric green proper json schema

- src/main/resources/data/ait/exterior/toyota_memorial.json
- src/main/resources/data/ait/sonic/copper.json
- src/main/resources/data/ait/sonic/coral.json
- src/main/resources/data/ait/sonic/crystalline.json
- src/main/resources/data/ait/sonic/fob.json
- src/main/resources/data/ait/sonic/mechanical.json
- src/main/resources/data/ait/sonic/renaissance.json
- src/main/resources/data/ait/sonic/singularity.json
- src/main/resources/data/ait/sonic/song.json
- src/main/resources/data/ait/sonic/type_100.json
This PR updates loyalty codec use. This is a follow up PR to #1154.
> fix: update loyalty schema in schemas

- .github/workflows/changelog.yml
> ci: use workflow dispatch trigger

- .github/workflows/pr-labeler-size.yml
> ci: fix auto assign

- src/main/java/dev/amble/ait/client/renderers/exteriors/ExteriorRenderer.java
- src/main/java/dev/amble/ait/core/tardis/animation/ExteriorAnimation.java
This PR simplifies exterior alpha calculations by removing unneeded calls.
Because performance.
> perf: simplify exterior alpha calculations

- .github/workflows/changelog.yml
- .github/workflows/publish.yml
Changelog is now automatically generated once release gets pushed to
Publishing release gets ran *after* changelog generation is completed
Now gets published to curseforge too
closes #1181
Ensures that the changelog is always up to date for releases
Curseforge playerbase now gets supported.
Edited workflow files
Not so sure on my logic for running though.
N/A
N/A
**Changelog**
N/A
> Release Workflow Changes

- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
I renamed the translatables of mark/set waypoint to save/load waypoint
closes #1146
People found it difficult to understand what "mark" and "set" meant, this is clearer.
I did *not* rename the classes *or* the identifier of the control
N/A
N/A
**Changelog**
> chore: mark/set waypoint -> save/load waypoint

- versioning.gradle
if branch is release, then the qualifier is ignored
changed to avoid accidental "beta" release onto platforms
updated `versioning.gradle.` to check if `branch` is release then set `qualifier` to blank
N/A
N/A
**Changelog**
N/A
> build: if branch is release, then the qualifier is ignored

- src/main/java/dev/amble/ait/data/schema/exterior/variant/dalek_mod/DalekModVariant.java
- src/main/java/dev/amble/ait/registry/impl/CategoryRegistry.java
- src/main/java/dev/amble/ait/registry/impl/exterior/ClientExteriorVariantRegistry.java
- src/main/java/dev/amble/ait/registry/impl/exterior/ExteriorVariantRegistry.java
Re-added the Dalek Mod Exteriors
They were randomly commented out
Just uncommented lines of existing code
> fix: Dalek Mod Exteriors being disabled

- src/main/java/dev/amble/ait/config/AITClientConfig.java
- src/main/java/dev/amble/ait/config/AITConfig.java
- src/main/java/dev/amble/ait/config/AITServerConfig.java
This PR fixes the config overwriting itself.
New implementation uses Cloth's/AutoConfig's `PartitioningSerializer`.
**Changelog**
:cl:
- fix: config no longer overwrites itself
> fix: config schizophrenia

- src/main/java/dev/amble/ait/core/blockentities/EngineBlockEntity.java
> fix: Engine not breaking its blocks

- src/main/java/dev/amble/ait/core/engine/impl/EngineSystem.java
> fix: tardis returning another subsystem core

- scripts/generate_changelogs.py
> fix: use only closed PRs for the changelog generator

- src/main/java/dev/amble/ait/client/tardis/manager/ClientTardisManager.java
- src/main/java/dev/amble/ait/data/TardisMap.java
This PR attempts at fixing the server sync crash.
First of all, this PR changes the `TardisMap` to be a `ConcurrentHashMap`.
**Changelog**
:cl:
- fix: no more seemingly random sync crashes
> fix: attempt fixing the sync crash

- src/main/java/dev/amble/ait/core/commands/EraseChunksCommand.java
MERGE THIS ASAP
**Changelog**
:cl:
- fix: FUCKING HELL
> FUCKING HELL

- src/main/java/dev/amble/ait/core/blocks/EngineBlock.java
- src/main/java/dev/amble/ait/core/engine/SubSystem.java
- src/main/java/dev/amble/ait/core/engine/block/SubSystemBlock.java
- src/main/java/dev/amble/ait/core/engine/block/SubSystemBlockEntity.java
- src/main/java/dev/amble/ait/core/engine/block/generic/GenericStructureSystemBlockEntity.java
- src/main/java/dev/amble/ait/core/engine/block/generic/GenericSubSystemBlock.java
- src/main/java/dev/amble/ait/core/engine/impl/ChameleonCircuit.java
- src/main/java/dev/amble/ait/core/engine/impl/DematCircuit.java
- src/main/java/dev/amble/ait/core/engine/impl/DesperationCircuit.java
- src/main/java/dev/amble/ait/core/engine/impl/EmergencyPower.java
- src/main/java/dev/amble/ait/core/engine/impl/EngineSystem.java
- src/main/java/dev/amble/ait/core/engine/impl/GravitationalCircuit.java
- src/main/java/dev/amble/ait/core/engine/impl/LifeSupportCircuit.java
- src/main/java/dev/amble/ait/core/engine/impl/ShieldsCircuit.java
- src/main/java/dev/amble/ait/core/engine/impl/Stabilisers.java
This PR fixes #1265.
**Changelog**
:cl:
- fix: store proper subsystem in the chest on reconfig
> fix: store proper subsystem in the chest on reconfig

- src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java
- src/main/java/dev/amble/ait/core/blockentities/control/RedstoneControlBlockEntity.java
- src/main/java/dev/amble/ait/core/blocks/control/RedstoneControlBlock.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/SecurityControl.java
This PR supposedly fixes #1269, but actually it doesn't. Why? After some research, it didn't seem like a bug.
...Also i've found something unoptimized so i decided to improve performance.
**Changelog**
:cl:
- perf: improved security check
> perf: improved security check

- src/main/java/dev/amble/ait/client/overlays/SonicOverlay.java
fix: sonic screen going dark????
fixes #1209 
**Changelog**
> fix: sonic screen going dark????

- src/main/java/dev/amble/ait/core/entities/GallifreyFallsPaintingEntity.java
This PR fixes #1259 (or should).
Apparently, mc is weird.
**Changelog**
:cl:
- fix: the painting no longer move up by one block
> fix: the painting no longer move up by one block

- src/main/java/dev/amble/ait/core/tardis/control/impl/HammerHangerControl.java
This PR fixes #1245.
**Changelog**
:cl:
- fix: provide a fallback sound for hammer hanger control
> fix: provide a fallback sound for hammer hanger control

- src/main/java/dev/amble/ait/core/blockentities/ExteriorBlockEntity.java
> refactor: done some stuff to exterior block entity

- src/main/java/dev/amble/ait/core/engine/SubSystem.java
This PR closes #1290. 
**Changelog**
:cl:
- fix: add generic subsystem core to the recovery chest
> fix: put generic subsystem cores alongside subsystems

- src/main/java/dev/amble/ait/client/tardis/manager/ClientTardisManager.java
- src/main/java/dev/amble/ait/core/tardis/TardisManager.java
- src/main/java/dev/amble/ait/core/tardis/manager/ServerTardisManager.java
- src/main/java/dev/amble/ait/core/tardis/manager/TardisFileManager.java
- src/main/java/dev/amble/ait/core/tardis/manager/old/DeprecatedServerTardisManager.java
- src/main/java/dev/amble/ait/data/TardisMap.java
This PR backports some tardis manager code from #1271. 
The #1271 PR has improved TM code, specifically the tardis maps which will be beneficial in use with the server.
See #1271.
**Changelog**
:cl:
- backport: backport some stuff from 1.3.0
- fix: no more log spam
> backport TM code from #1271

- src/main/java/dev/amble/ait/compat/DependencyChecker.java
- src/main/java/dev/amble/ait/config/AITClientConfig.java
turned off boti (people just wont look at the config like the people they are and will just report that their boti wont work :sob:)
**Changelog**
> fix: turned off boti by defualt

- src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java
> bring back handbrake sfx pR

- src/main/java/dev/amble/ait/client/renderers/exteriors/ExteriorRenderer.java
- src/main/java/dev/amble/ait/core/tardis/animation/v2/AnimationHolder.java
- src/main/java/dev/amble/ait/core/tardis/animation/v2/TardisAnimation.java
- src/main/java/dev/amble/ait/core/tardis/animation/v2/keyframe/AnimationKeyframe.java
- src/main/java/dev/amble/ait/core/tardis/animation/v2/keyframe/KeyframeTracker.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/AnimatedTravelHandler.java
Animation Keyframes can now offset and rotate the TARDIS
funsies
`InterpolatedValue` 
cba
N/A
**Changelog**
api(anim): can now define keyframe rotation
api(anim): can now define keyframe position offset
> Animations: Interpolating Values & Rotating & Positioning

- src/main/java/dev/amble/ait/client/util/TooltipUtil.java
- src/main/java/dev/amble/ait/core/blocks/ArtronCollectorBlock.java
- src/main/java/dev/amble/ait/core/blocks/CoralPlantBlock.java
- src/main/java/dev/amble/ait/core/blocks/EnvironmentProjectorBlock.java
- src/main/java/dev/amble/ait/core/blocks/FabricatorBlock.java
- src/main/java/dev/amble/ait/core/blocks/MatrixEnergizerBlock.java
- src/main/java/dev/amble/ait/core/blocks/PowerConverterBlock.java
- src/main/java/dev/amble/ait/core/engine/item/SubSystemItem.java
- src/main/java/dev/amble/ait/core/item/WaypointItem.java
- src/main/java/dev/amble/ait/core/item/blueprint/BlueprintItem.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
added shift to display info for items with a hint fixes #1333
**Changelog**
> feat: added shift for more info for items with info

- gradle.properties
change version and qualifier to 1.3.0 and alpha
> build(ver): 1.3.0-alpha

- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
- src/main/java/dev/amble/ait/registry/impl/HandlesResponseRegistry.java
removed handles summon command
ouro told me to
i blew it up
**Changelog**
:cl:
- Removed handles ability to summon the TARDIS.
> chore: removed handles summon command

- src/main/resources/data/ait/loot_tables/chests/cult_chest_one.json
- src/main/resources/data/ait/loot_tables/chests/space_ship.json
im to lazy to fill this out i removed the mercury disc from the loot tables since that was removed.
**Changelog**
:cl:
- Fix: loottables
> fix: loottables

- src/main/java/dev/amble/ait/api/ConsumableBlock.java
- src/main/java/dev/amble/ait/core/blocks/PowerConverterBlock.java
- src/main/java/dev/amble/ait/mixin/HopperBlockEntityMixin.java
- src/main/resources/ait.mixins.json
hopper intake items on power converter +made a interface for non blockentitys to intake items through hoppers 
**Changelog**
> feat: hopper intake on power converter

- src/main/java/dev/amble/ait/core/tardis/handler/ShieldHandler.java
I accidently had the shiled push thing on the easter egg branch, whoopsie.
This literly just reverts it
Oops
Reverted the shield code, literly the same as before.
**Changelog**
:cl:
- Fixed shields
> fix: oopsie

- src/main/java/dev/amble/ait/client/boti/RiftBOTI.java
- src/main/java/dev/amble/ait/client/boti/TardisDoorBOTI.java
- src/main/java/dev/amble/ait/client/renderers/VortexUtil.java
- src/main/java/dev/amble/ait/client/renderers/entities/FlightTardisRenderer.java
- src/main/java/dev/amble/ait/client/util/SkyboxUtil.java
…war_second.png" and "war_third.png", if they dont exist thats a-okay
**Changelog**
> Feature: Vortex Layers (pls no judge the code) 

- src/main/java/dev/amble/ait/core/AITDamageTypes.java
- src/main/java/dev/amble/ait/core/item/KeyItem.java
- src/main/java/dev/amble/ait/core/tardis/handler/InteriorChangingHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/ServerAlarmHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/CrashableTardisTravel.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
Alarms now display a message every cloister toll as their reason & can countdown
closes #1350
Allows the user to distinguish between alarms and figure out why they're happening. Makes them more useful.
`Alarm` interface and `Countdown` implementation
`ServerAlarmHandler` has an `ArrayQueue` of alarms to be ran and the current alarm
`Alarm` has a priority, prioritised alarms (eg countdowns) ignore the queue
`AlarmType` enum for generic reusables
N/A
deprecated `ServerAlarmHandler#enabled` as there is logic in the methods now, use `#enable` `#disable` `#isEnabled` instead
**Changelog**
:cl:
feat: informative alarms
> Informative Alarms

- src/main/java/dev/amble/ait/client/renderers/decoration/PlaqueRenderer.java
- src/main/java/dev/amble/ait/core/blockentities/PlaqueBlockEntity.java
- src/main/java/dev/amble/ait/core/blocks/PlaqueBlock.java
Allows the player to edit the tardis type number via a nametag.
Yes im aware their not a global thingy so not all plaques are the same but thats on purpose to allow for more customization.
Is cool
To lazy
**Changelog**
🆑 
- Editable TARDIS Type number!
> feat: editable TARDIS type number!

- src/main/java/dev/amble/ait/core/AITSounds.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/PowerControl.java
removed mad man thingy for now till dian makes new music cuz copyright lol
**Changelog**
:cl:
- Temporarly changed easter egg music till dian makes better one
> chore: temporarly removed music since thats kinda copyrighted lol

- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
- src/main/java/dev/amble/ait/datagen/datagen_providers/AITAchievementProvider.java
Added an advancement when the player crafts a stat remote
closes #1452
It's a big achievement
Updated `AITAchievementProvider`
> feat(advancement): stat remote advancement

- src/main/java/dev/amble/ait/core/AITItems.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
> fix: rename hammer -> mallet

- src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java
play knock sound & spawn particle when on cooldown
closes #1423
read issue
> feat: indicate that control is on cooldown

- src/main/java/dev/amble/ait/core/AITTags.java
- src/main/java/dev/amble/ait/core/entities/FallingTardisEntity.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/ConsolePortControl.java
what addie wanted or somthin fixes #1482
**Changelog**
> feat: added music disc insertable tag

- src/main/java/dev/amble/ait/AITMod.java
- src/main/java/dev/amble/ait/core/util/CustomTrades.java
renamed `dev.amble.ait.core.util.CustomTrades.registerCustomTrades` to `dev.amble.ait.core.util.CustomTrades.register`
none
none, pure renaming
none
beware of the transition from `dev.amble.ait.core.util.CustomTrades.registerCustomTrades` to `dev.amble.ait.core.util.CustomTrades.register`.
**Changelog**
included in the commit message.
> fix: renamed a method for sake of sanity

- src/main/java/dev/amble/ait/core/drinks/DrinkUtil.java
- src/main/java/dev/amble/ait/core/item/DrinkItem.java
made milk clear status effects and made an empty mug not drinkable.
This PR fixes https://github.com/amblelabs/ait/issues/1257
**Changelog**
🆑 
fix: empty mug is drinkable 
feat: made milk mug clear status effects
> fix: empty mug is drinkable

- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
Rename "Type 100" sonic to "Frontier"
closes #1508
To match the interior
Changed a datagen line
> chore(sonic): Type 100 -> Frontier

- CREDITS.md
- README.md
- src/main/resources/fabric.mod.json
> fix(README): fixed my nickname because nobody here can ever get it right

- src/main/java/dev/amble/ait/core/item/blueprint/BlueprintItem.java
- src/main/java/dev/amble/ait/core/item/blueprint/BlueprintRegistry.java
Just like #1542 but for blueprints.
> fixes #1541 pt.2

- src/main/resources/assets/minecraft/texts/splashes.txt
**Changelog**
🆑
- add: new splashes
> add new splashes

- src/main/java/dev/amble/ait/client/sounds/SoundHandler.java
- src/main/java/dev/amble/ait/client/sounds/flight/ClientFlightHandler.java
- src/main/java/dev/amble/ait/client/sounds/flight/ExteriorFlightSound.java
- src/main/java/dev/amble/ait/client/sounds/flight/FlightSoundPlayer.java
- src/main/java/dev/amble/ait/client/sounds/flight/IFlightSoundPlayer.java
- src/main/java/dev/amble/ait/client/sounds/flight/InteriorFlightSound.java
- src/main/java/dev/amble/ait/core/tardis/animation/v2/AnimationHolder.java
Now when you do the handbrake & throttle combo to make the slowed flight sound play, it plays at exterior and with alpha fx
Looks cool
https://streamable.com/g70wik
> feat: alpha fx for handbrake groans

- src/main/java/dev/amble/ait/core/advancement/TardisCriterions.java
- src/main/java/dev/amble/ait/core/blocks/PowerConverterBlock.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
- src/main/java/dev/amble/ait/datagen/datagen_providers/AITAchievementProvider.java
If you feed the power converter food item it grants a special achievement
closes #1487 
Ok
no
> feat: power converter achievement

- src/main/java/dev/amble/ait/core/item/KeyItem.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/HailMaryControl.java
This PR removes the fuel cost of toggling the Hail Mary protocol and instead adds it to its trigger cost.
Two years ago (29-DEC-2023) a fuel cost was added for when the Hail Mary control was toggled on or off.
Since last year though (07-DEC-2024) a fuel cost has been added for when the protocol actually *triggers* (in https://github.com/amblelabs/ait/blob/main/src/main/java/dev/amble/ait/core/item/KeyItem.java#L167).
Therefore the cost for *toggling* the control seems redundant now, as well as it doesn't make sense that merely toggling a control on or off would consume fuel.
(No other control has a cost on toggling, so this is very much a remnant from back in the day.)
This PR proposes to move the toggle cost to the trigger cost, to bring it in line with all other toggleable controls.
The …
> Merge Hail Mary toggle-cost into trigger-cost

- src/main/resources/data/ait/tardis_names.json
Cave Johnson as a name in refrence to the meow meow meow sound literly being him
idk man
idk man
**Changelog**
:cl:
- Cave Johnson is now 1 of the possible TARDIS names
> feat: the funny

- .github/ISSUE_TEMPLATE/1-bug-report.yaml
- .github/workflows/update-bug-form.yml
added a github action for when the release branch gets commited the update then it takes the update from gradle.properties and adds that to the list
saves us a bit of time and if we forget to then yeah
> Bug Report Automatic Updater

- src/main/java/dev/amble/ait/client/sounds/flight/ExteriorFlightSound.java
- src/main/java/dev/amble/ait/client/sounds/flight/InteriorFlightSound.java
- src/main/java/dev/amble/ait/core/tardis/TardisDesktop.java
- src/main/java/dev/amble/ait/core/tardis/TardisExterior.java
- src/main/java/dev/amble/ait/core/tardis/animation/v2/TardisAnimation.java
- src/main/java/dev/amble/ait/core/tardis/animation/v2/datapack/DatapackAnimation.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/TravelHandler.java
- src/main/java/dev/amble/ait/core/tardis/util/NetworkUtil.java
meow. meow meow meow meow, meow. meow meow meow meow meow. meow.
> fix: datapack sounds on servers meowing/erroneous

- .github/ISSUE_TEMPLATE/1-bug-report.yaml
Added 1.2.7 to the bug report version list
> chore: add 1.2.7 to version list

- src/main/java/dev/amble/ait/core/tardis/handler/SiegeHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/TravelHandler.java
- src/main/java/dev/amble/ait/module/gun/core/item/StaserBoltMagazine.java
- src/main/java/dev/amble/ait/module/planet/mixin/gravity/BoatEntityMixin.java
I'm just fixing bugs.
I'm just fixing bugs.
I'm just fixing bugs.
**Changelog**
> Fix: Assorted Bugs

- .github/ISSUE_TEMPLATE/1-bug-report.yaml
Added forge version to bug report list
so people dont report a bug on fabric when they are on forge 
added `AIT Forger 1.0.0+1.2.7` to versions list
NA
NA
**Changelog**
:cl:
- chore: added forge version to bug report list
> modloader option on bug report

- src/main/java/dev/amble/ait/client/config/AITClientConfig.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
fixed missing translations for the ait-config
closes #1653 
https://github.com/user-attachments/assets/491ad60f-f1fe-4c75-8d81-4fd6f603706d
> fix: missing translations for ait-config

- src/main/java/dev/amble/ait/core/advancement/TardisCriterions.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/PowerControl.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
- src/main/java/dev/amble/ait/datagen/datagen_providers/AITAchievementProvider.java
added attack eyebrows easter egg advancement
closes #1523 
https://github.com/user-attachments/assets/966aa0b3-c9cc-4c6b-8248-9d8f9609ef69
changelog
🆑 
- add attack eyebrow advancement reference
> feat: attack eyebrows advancement

- .github/ISSUE_TEMPLATE/1-bug-report.yaml
Added ~1.2.8~ `BETA` to the bug report version list
> chore: add BETA to version dropdown

- .github/ISSUE_TEMPLATE/1-bug-report.yaml
update bug report version drop down to 1.2.9
update bug report version drop down to 1.2.9
update bug report version drop down to 1.2.9
update bug report version drop down to 1.2.9
update bug report version drop down to 1.2.9
:cl:
- update bug report version drop down to 1.2.9
> update bug report version drop down to 1.2.9

- src/main/java/dev/amble/ait/config/AITServerConfig.java
This PR blacklists space from travel.
Space is kinda buggy and @Loqor did greenlight its removal so we're going to be phasing it out slowly.
> chore: blacklist space from travel

- src/main/java/dev/amble/ait/core/devteam/DevTeam.java
update the dev team list
update the dev team list
added monke (me), pan, saturn, maggie, k king, crow
🆑 
- update the dev team list
> update the dev team list

- CHANGELOG.md
Add missing changelog entry for PR #1775 that was the result of me forgetting to check a PR for having a changelog section.
Because we want to inform the players of the change.
I added it by hand, taking already existing entries as a template.
**Changelog**
Doesn't need one, as it would lead to changelog-ception.
> Add changelog for PR #1775 to CHANGELOG.md 

- src/main/java/dev/amble/ait/api/tardis/TardisEvents.java
- src/main/java/dev/amble/ait/client/sounds/hum/exterior/ExteriorHumHandler.java
- src/main/java/dev/amble/ait/core/blocks/ExteriorBlock.java
- src/main/java/dev/amble/ait/core/commands/DebugCommand.java
- src/main/java/dev/amble/ait/core/tardis/TardisExterior.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/ThrottleControl.java
- src/main/java/dev/amble/ait/core/tardis/handler/BiomeHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/ChameleonHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/DoorHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/RealFlightHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/SiegeHandler.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
- src/main/java/dev/amble/ait/module/planet/core/space/planet/PlanetRegistry.java
- src/main/java/dev/amble/ait/registry/impl/CategoryRegistry.java
- src/main/java/dev/amble/ait/registry/impl/exterior/ClientExteriorVariantRegistry.java
- src/main/java/dev/amble/ait/registry/impl/exterior/ExteriorVariantRegistry.java
- src/main/java/dev/drtheo/gaslighter/Gaslighter3000.java
- src/main/java/dev/drtheo/gaslighter/api/FakeBlockEvents.java
- src/main/java/dev/drtheo/gaslighter/mixin/ServerPlayNetworkHandlerMixin.java
- src/main/resources/data/ait/worldgen/configured_feature/cactus.json
This PR adds the adaptive exterior.
Because it's a cool feature.
Adaptive exterior does silly stuff like chunk data manipulation (in network) to make the TARDIS look like a certain configured worldgen feature from the biome where the exterior is placed. If there's no viable configured feature, then the exterior will try to set itself to look like a block beneath. If there's not any, it will look like a default white shell exterior.
[AIT Chameleon Land.webm](https://github.com/user-attachments/assets/0f81a323-f306-4ab8-872e-6f3d7229c2c6)
[AIT Chameleon Demat.webm](https://github.com/user-attachments/assets/dafae032-cf54-4ad9-bf8f-066f84ca28ab)
None
**Changelog**
:cl:
- add: adaptive exterior
> feat: adaptive exterior

- src/main/java/dev/amble/ait/module/gun/core/entity/StaserBoltEntity.java
buff stasers to deal more damage on entities
too low before
**Changelog**
:cl:
- tweak: buffed staser damage on entities
> buff stasers

- src/main/java/dev/amble/ait/AITMod.java
- src/main/java/dev/amble/ait/api/tardis/link/LinkableItem.java
- src/main/java/dev/amble/ait/core/commands/UnLinkCommand.java
Adds a /ait unlink command
As per moderators' request.
Removes the TARDIS id from the item stack.
**Changelog**
:cl:
- add: /ait unlink
> feat: /ait unlink command

- src/main/java/dev/amble/ait/client/sounds/hum/exterior/ExteriorHumHandler.java
Closes #1845
**Changelog**
:cl:
- fix: no more exterior hum when cloaked
> No exterior hum when cloaked

- src/main/java/dev/amble/ait/client/models/items/HandlesModel.java
> fix: handles in item frame

- src/main/java/dev/amble/ait/client/screens/MonitorScreen.java
> fix: datapack exteriors floating in screen

- src/main/resources/data/ait/fx/animation/type/self_destruct.json
fixed the self destruct sound so it doesnt meow anymore
It was broken before hand
added `"sound": "ait:tardis/crumple"` to the `self_destruct.json` in `data/ait/fx/animation/type/`
(Just the same sound as my last pr :shrug: ) 
**Changelog**
:cl:
- fix: self destruct sound
> fix: self destruct sound

- src/main/java/dev/amble/ait/client/screens/interior/InteriorSettingsScreen.java
**Changelog**
:cl:
- fix: missing desktops no longer crash your game when you open the monitor
> no more missing desktop crash
