- src/main/java/loqor/ait/api/TardisEvents.java
- src/main/java/loqor/ait/core/tardis/handler/ChameleonHandler.java
- src/main/java/loqor/ait/core/tardis/handler/DoorHandler.java
When The Adaptive Tardis Door is was closed, the disguise would disappear, and when it was open the disguise would appear. (The Opposite should be true)
Described in [This Issue](https://github.com/pavatus/ait/issues/849)
This was caused by a problem where the ChameleonHandler class wasn't getting up to date information on the door state because it was invoked by the USE_DOOR event, which ran before the door was actually updated. 
I've created a new event called DOOR_USED, which is invoked after the door interaction has finished, which fixes the issue.
> Fixed Adaptive Tardis Exterior door 

- src/main/java/dev/amble/ait/core/item/sonic/OverloadSonicMode.java
- src/main/java/dev/amble/ait/core/item/sonic/ScanningSonicMode.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
Added a way to scan entity health and blocks to see what tool they need and their blast res plus also shatter glass
saturn wanted it and it gives scanning mode more use
⚔
- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://amblelabs.github.io/ait-wiki/guidelines).
- [X ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
:cl:
- add: Added Glass Blocks to be shattered
- add: Added Entity Health Scanning
- add: Added Block Tool Requirement Scanning
-->
> Sonic block and entity scanning

- src/main/java/dev/amble/ait/core/tardis/control/impl/DimensionControl.java
- src/main/java/dev/amble/ait/core/util/WorldUtil.java
- src/main/java/dev/amble/ait/core/world/TardisServerWorld.java
This PR fixes #1121.
- `WorldUtil.worlds` is now `WorldUtil.WORLDS`
- `WorldUtil.blacklisted` is now `WorldUtil.BLACKLIST`
- Removed `WorldUtil.isOpen`, use `WorldUtil.isBlacklisted` instead
**Changelog**
:cl:
- fix: ignore tardis dimensions when generating world cache
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #1134 
- <kbd>&nbsp;1&nbsp;</kbd> #1133 👈
> fix: tardis dimension should be excluded from travelling (#1121)

- src/main/java/dev/amble/ait/core/blockentities/EnvironmentProjectorBlockEntity.java
- src/main/java/dev/amble/ait/core/blocks/EnvironmentProjectorBlock.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/DimensionControl.java
- src/main/java/dev/amble/ait/core/util/WorldUtil.java
- src/main/java/dev/amble/ait/core/world/TardisServerWorld.java
Use `WorldUtil` to ignore blacklisted dimensions from appearing in environment projector.
TARDIS dimensions would quickly build up and clutter the environment projector.
**Changelog**
:cl:
- fix: use filtered world list in environment projector
- refactor: remove unused parameters from environment projector block entity
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #1134 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #1133
> fix: respect world blacklist for environment projector

- build.gradle
Remove spotless check that fails the build. 
Instead of enforcing formatting on EVERY build, apply it every once in a while in a separate PR.
> ci: disable spotless failure by default

- src/main/java/dev/amble/ait/api/TardisEvents.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/AnimatedTravelHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/TravelHandler.java
Instead of doing safe pos search on the main thread of remat, do it off the main thread and then run the rest of the code synchronously.
This also should fix #1148.
The PR uses AsyncLocatorUtil's executor service. To stop the animation from playing, a new field was brought in to `TravelHandler`: `waiting`. `AnimatedTravelHandler` got a `shouldTickAnimation` abstract method, which replaces the previously hardcoded if statement.
- `TardisEvents.Result.result()` -> `TardisEvents.Result.value()`
**Changelog**
:cl:
- fix: Rematerialization is no longer as heavy on performance as it was before
> perf: use async to find safe position before remat 

- .github/labeler.yml
This PR makes it so the labeler workflow applies "C: No Java" or "C: Structures" and etc insted of "Changes: whatever"
We use the short label names on github.
> ci: use short label names, as they are in github

- src/main/java/dev/amble/ait/config/AITConfig.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/DimensionControl.java
- src/main/java/dev/amble/ait/core/util/WorldUtil.java
- src/main/java/dev/amble/ait/registry/impl/MoodEventPoolRegistry.java
This PR splits the `WORLDS_BLACKLIST` option in the config into 2: `WORLDS_BLACKLIST` and `TRAVEL_BLACKLIST`. 
Fixes #1152.
This is used in environment projector and the dimension control. You shouldn't be able to travel into the time vortex dimension, but the time vortex dimension should otherwise be available.
**Changelog**
:cl:
- add: `TRAVEL_BLACKLIST` config option to blacklist worlds from travel.
> feat: split world blacklist into travel and open world blacklists

- .github/labeler.yml
This PR fixes wrong file globs for labeler CI.
> ci: use proper file glob for structures, textures and sound in labeler

- src/main/java/dev/amble/ait/data/Loyalty.java
This PR streamlines the use of the loyalty codec.
The previous implementation was dumb.
This PR utilizes `Codec.either`.
Everything that uses the loyalty codec must use the new codec.
E.g.
```json
"loyalty": {
"type": "OWNER"
}
```
should be
```json
"loyalty": "OWNER"
```
> feat!: use an either in the loyalty codec

- src/main/java/dev/amble/ait/core/util/WorldUtil.java
This PR fixes one of the previous PRs. It updates the filter to point to the proper world list, as well as invert the "is tardis dimension" check.
> fix: add the world to proper world list, ignore tardis dimension

- src/main/java/dev/amble/ait/data/properties/Property.java
- src/main/java/dev/amble/ait/data/properties/Value.java
This PR fixes problems with syncing properties that use collections (e.g. unlockables).
Now all property types can provide a `sameRef` flag (defaults to true). If it's `true` the reference check will be enforced.
> Property same reference fix check

- src/main/java/dev/amble/ait/core/engine/impl/DematCircuit.java
- src/main/java/dev/amble/ait/core/tardis/handler/FuelHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/TravelHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/TravelHandlerBase.java
This PR makes it so `FuelHandler` doesn't subtract the power during materialization or flight when the tardis is in growth.
See #1160
> fix: dont subtract artron when in growth

- src/main/java/dev/amble/ait/client/models/coral/CoralGrowthDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/BookshelfDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/BoothDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/CapsuleDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/ClassicDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/ClassicHudolinDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/DalekModDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/EasterHeadDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/GeometricDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/PlinthDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/PoliceBoxDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/PresentDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/RenegadeDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/StallionDoorModel.java
- src/main/java/dev/amble/ait/client/models/doors/TardimDoorModel.java
This is a follow up PR to the client tardis refs PR. It updates the door models to use the client tardis ref instead of getting it from the block entity.
> fix: use client tardis ref in door models

- .github/workflows/pr-labeler-size.yml
This PR changes the workflows to automatically set reviewers depending on PR size.
As requested by @duzos.
> ci: automagically assign reviewers based on PR size

- src/main/resources/data/ait/loot_tables/chests/cult_chest_one.json
- src/main/resources/data/ait/loot_tables/chests/space_ship.json
I made music discs spawn in AIT structures
This makes it so players who are adventuring and find AIT structures are also bound to find our discs.
I added the items to the loot tables
X
**Changelog**
:cl:
- feat: AIT discs spawn in AIT structures
> feat: music discs spawn in structures

- src/main/java/dev/amble/ait/client/boti/TardisExteriorBOTI.java
- src/main/java/dev/amble/ait/client/models/coral/CoralGrowthExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/BookshelfExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/BoothExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/CapsuleExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/ClassicExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/ClassicHudolinExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/DoomExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/EasterHeadModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/ExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/GeometricExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/JakeTheDogExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/PipeExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/PlinthExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/PoliceBoxCoralModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/PoliceBoxModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/PresentExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/RenegadeExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/SiegeModeModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/StallionExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/TardimExteriorModel.java
- src/main/java/dev/amble/ait/client/models/exteriors/advent/DalekModExteriorModel.java
- src/main/java/dev/amble/ait/client/renderers/exteriors/ExteriorRenderer.java
This PR refactors the exterior models to use the passed client tardis ref instead of fetching it.
Increased stability against the race condition.
> refactor: use passed client tardis ref in exterior models

- .github/workflows/pr-labeler-approve.yml
This PR updates the workflows to use `BOT_TOKEN` from our bot account instead of `CI_TOKEN` (which was my personal token).
It's better to do automization on a bot account.
> ci: use bot token instead of ci token

- src/main/java/dev/amble/ait/core/item/sonic/ScanningSonicMode.java
main hand to scan blocks/entities
off hand to scan region
closes #1106
As the range of block scan is quite large, you have to look in air to scan a region
This is changed by disabling the block scan in off hand mode, allowing region scans to become easier.
add "isMainHand" check to `ScanningSonicMode#process`
N/A
N/A
**Changelog**
:cl:
- feat: sonic scan mode is now hand-dependent (main = blocks/entities, off = region)
> feat: sonic scan mode is hand-dependent

- src/main/java/dev/amble/ait/core/blockentities/EngineBlockEntity.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
The engine now spawns cables adjacent to it and barrier blocks in the corner
closes #1168
This is done as people were confused why they couldnt properly link up the engine
It also fixes the representation, as the engine was a large 3x3 structure but only had a small hitbox
Created `tryPlaceFillBlocks` `tryRemoveFillBlocks` methods which attempt to place and remove these blocks on place/broken
N/A
N/A
**Changelog**
:cl:
- feat: engine comes with cables, requires 3x3 space
> feat: engine comes with cables, requires 3x3 space

- src/main/java/dev/amble/ait/client/AITModClient.java
- src/main/java/dev/amble/ait/client/boti/BOTI.java
- src/main/java/dev/amble/ait/compat/DependencyChecker.java
Added a HUD warning which shows up if the client is missing indium and has a non-nvidia gpu
closes #1182 
Not tested as I dont have AMD GPU
Indium is required for AMD GPUs as it causes rendering issues
Added `tryWarn` and a check for `indium` existing
N/A
N/A
**Changelog**
:cl:
- add: show a warning for AMD GPUs without Indium
> BOTI Warning for AMD GPUs without Indium

- src/main/java/dev/amble/ait/client/renderers/exteriors/ExteriorRenderer.java
Moved shield rendering to the end, so it can be rendered over the exterior
fixes the exterior going invisible when shield is on
**Changelog**
> fix: exterior not rendering behind the shields

- src/main/java/dev/amble/ait/client/overlays/SonicOverlay.java
Moved sonic overlay upward
closes #1210
Before it was overlapping with crosshair
> fix: position of sonic overlay

- src/main/java/dev/amble/ait/client/AITModClient.java
- src/main/java/dev/amble/ait/client/boti/BOTI.java
- src/main/java/dev/amble/ait/client/renderers/SonicRendering.java
- src/main/java/dev/amble/ait/core/blockentities/EngineBlockEntity.java
- src/main/java/dev/amble/ait/core/blockentities/ExteriorBlockEntity.java
- src/main/java/dev/amble/ait/core/blocks/ExteriorBlock.java
- src/main/java/dev/amble/ait/core/engine/SubSystem.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
Invalid exteriors get deleted
patch for #477
RWF causes dupe exteriors, temp patch until 1.3.0
Added a method which checks the expected dimension and position & deletes the exterior if they dont match.
Is ran on use and on collision
> chore: delete invalid exteriors on use and on collision

- src/main/java/dev/amble/ait/core/commands/DataCommand.java
This PR changes the data command to parse the json element itself instead of turning it into a string.
This allows players (admins) to set doubles, integers and more.
**Changelog**
:cl:
- fix: allow to use any json values in /ait data
> fix: /ait data command accepts any json element now

- src/main/resources/data/ait/loot_tables/chests/cult_chest_one.json
added the ait:staser_bolt_magazine to the cult_chest_one lootable
it was not in any loottable and is not craftable
**Changelog**
:cl:
fix:  ait:staser_bolt_magazine not being in loottables
> fix: ait:staser_bolt_magazine not being in loottables

- src/main/java/dev/amble/ait/client/screens/AstralMapScreen.java
- src/main/java/dev/amble/ait/module/planet/mixin/gravity/LivingEntityMixin.java
Planets/Space without oxygen requires a full spacesuit to breathe now
You could take every piece off but the chestplate and be fine
just added hasFullSpacesuit() boolean to the mixin.
**Changelog**
:cl:
- Fixed being able to breathe where you shouldn't be with your helmet off.
> Fixed Spacesuit Breathing

- src/main/java/dev/amble/ait/module/planet/core/PlanetBlocks.java
- src/main/java/dev/amble/ait/module/planet/core/PlanetItems.java
I made the planet themed swords less OP, i also fixed all the planet block loottables and pickaxe level being non existant
The swords had an attack speed of 7 (minecrafts default for most swords is 1.6). Most of the planet blocks did not drop their items.
- added `@PickaxeMineable(tool = PickaxeMineable.Tool.IRON)` to blocks that where missing it in the `PlanetBlocks` class
- changed `ANORTHOSITE_SWORD` and `MARTIAN_STONE_SWORD` `attackspeed` from `3` to `-2.4` in the `PlanetItems` class
No "in-game" changes where made (just code based)
Nothing was broken in this branch, just fixed 
**Changelog**
- Fix: made planet swords have less attack speed (less OP)
- Fix: planet block loottables and pickaxeminable level
> fix: PlanetBlocks loottables / swords are less OP

- src/main/java/dev/amble/ait/client/renderers/wearables/RespiratorFeatureRenderer.java
- src/main/java/dev/amble/ait/mixin/client/rendering/ArmorStandEntityRendererMixin.java
- src/main/java/dev/amble/ait/module/planet/client/renderers/wearables/SpacesuitFeatureRenderer.java
- src/main/resources/ait.mixins.json
I added a mixin to the ArmorStandEntityRenderer to add our features so they render on the model properly, and I modified the RenderFeatures we have to allow for the armor stand's BipedModel versus just using the player's model.
:cl:
- fix: armor stand renders respirators and other stuff correctly now
> Armor Stand Rendering For Our Custom Render Features

- src/main/java/dev/amble/ait/core/handles/HandlesResponse.java
- src/main/java/dev/amble/ait/registry/impl/HandlesResponseRegistry.java
This PR fixes #1270.
Previously, handles allowed to bypass the P19 protocol.
The PR adds a "requiresSudo" method, which, when overriden, can define whether a certain command requires a security check when P19 is on.
**Changelog**
:cl:
- fix: handles can no longer bypass P19
> fix: handles can no longer bypass security protocols

- src/main/java/dev/amble/ait/core/tardis/handler/InteriorChangingHandler.java
This PR automatically disables autopilot after growth tardis lands.
**Changelog**
:cl:
- fix: disable autopilot after growth land
> fix: disable autopilot after growth land

- src/main/java/dev/amble/ait/core/tardis/control/impl/SecurityControl.java
- src/main/java/dev/amble/ait/core/tardis/handler/permissions/PermissionHandler.java
This PR fixes min loyalty setting (#1263). Previously, this value was ignored.
**Changelog**
:cl:
- fix: dont ignore isomophic level setting
> fix: use min loyalty security setting properly

- src/main/java/dev/amble/ait/core/blockentities/ExteriorBlockEntity.java
- src/main/java/dev/amble/ait/core/blocks/ExteriorBlock.java
- src/main/java/dev/amble/ait/core/tardis/handler/SiegeHandler.java
- src/main/java/dev/amble/ait/core/tardis/util/TardisUtil.java
This PR improves siege mode performance.
Instead of ticking every non 20th tick (1, 2, 3, ..., 18, 19, 21) it will tick every 10th tick now. 
Also removed useless exterior block checks.
**Changelog**
:cl:
- perf: siege mode is no longer as performance heavy as it was
> perf: improve siege tardis ticking

- src/main/java/dev/amble/ait/core/tardis/manager/TardisFileManager.java
- src/main/java/dev/amble/ait/core/tardis/manager/old/DeprecatedServerTardisManager.java
This PR fixes the "failed to load tardis" log spam.
This PR uses a set of UUIDs to ignore specific tardis IDs.
**Changelog**
:cl:
- fix: removed "missing tardis" log spam
> fix: no more log spam

- src/main/java/dev/amble/ait/core/tardis/TardisDesktop.java
- src/main/java/dev/amble/ait/core/world/TardisServerWorld.java
This PR makes it so the interior drops get removed after interior change sequence.
Closes #1296.
Previously, all the stuff like flower pots, signs, paintings, item frames, and etc would drop in the interior as entities after the interior reconfig. Now - they dont.
**Changelog**
:cl:
- fix: kill interior drops after interior change
> fix: kill interior drops on interior change end

- src/main/java/dev/amble/ait/core/tardis/ServerTardis.java
- src/main/java/dev/amble/ait/core/tardis/handler/InteriorChangingHandler.java
- src/main/java/dev/amble/ait/core/tardis/manager/old/DeprecatedServerTardisManager.java
This PR fixes the interior not re-queuing after a restart.
This PR fixes a long standing issue in AIT: when a player queues an interior change and restarts the server (rejoins the world) - the interior change doesn't queue, the doors stay locked and etc.
**Changelog**
:cl:
- fix: re-queue the interior change on restart
> fix: requeue the interior change on restart

- src/main/java/dev/amble/ait/AITMod.java
- src/main/java/dev/amble/ait/core/commands/DataCommand.java
- src/main/java/dev/amble/ait/core/commands/DebugCommand.java
- src/main/java/dev/amble/ait/core/commands/FlightCommand.java
- src/main/java/dev/amble/ait/core/commands/FuelCommand.java
- src/main/java/dev/amble/ait/core/commands/GetCreatorCommand.java
- src/main/java/dev/amble/ait/core/commands/GetNameCommand.java
- src/main/java/dev/amble/ait/core/commands/LinkCommand.java
- src/main/java/dev/amble/ait/core/commands/ListCommand.java
- src/main/java/dev/amble/ait/core/commands/LoadCommand.java
- src/main/java/dev/amble/ait/core/commands/RemoveCommand.java
- src/main/java/dev/amble/ait/core/commands/SetLockedCommand.java
- src/main/java/dev/amble/ait/core/commands/SetMaxSpeedCommand.java
- src/main/java/dev/amble/ait/core/commands/SetNameCommand.java
- src/main/java/dev/amble/ait/core/commands/SetRepairTicksCommand.java
- src/main/java/dev/amble/ait/core/commands/SetSiegeCommand.java
- src/main/java/dev/amble/ait/core/commands/SummonTardisCommand.java
- src/main/java/dev/amble/ait/core/commands/TeleportInteriorCommand.java
- src/main/java/dev/amble/ait/core/commands/ThisTardisCommand.java
- src/main/java/dev/amble/ait/core/commands/TravelDebugCommand.java
- src/main/java/dev/amble/ait/core/commands/TriggerMoodRollCommand.java
- src/main/java/dev/amble/ait/core/commands/UnlockCommand.java
- src/main/java/dev/amble/ait/core/commands/argument/TardisArgumentType.java
This PR makes it so you can use `~` to point to the tardis you're currently in and `^` to point at a linked block entity instead of using a full tardis UUID.
This PR is a (better) alternative to #1251.
Previously, you had to find the tardis, then go inside it using a command, then copying its UUID, then doing something else. Now you can just look at it, or just be inside.
- `GetInsideCommand` -> `ThisCommand`
**Changelog**
:cl:
- add: now you can use ~ and ^ to point at tardises inside of commands
> feat: you can now reference tardises around in commands (^ and ~)

- src/main/java/dev/amble/ait/core/tardis/manager/old/DeprecatedServerTardisManager.java
This PR fixes a crash that happens because of attempting to load a tardis when the file manager is locked.
**Changelog**
:cl:
- fix: no more random crashes when trying to load a tardis during lock
> fix: don't load the tardis when the file manager is locked

- src/main/java/dev/amble/ait/core/world/TardisServerWorld.java
This PR fixes a crash in `TardisServerWorld`.
The crash is caused by the lazily loaded tardis value not being null checked. The PR updates the code to use a getter.
**Changelog**
:cl:
- fix: no more random reconfig crashes
> fix: use tardis getter in tardis server world to prevent a crash

- src/main/java/dev/amble/ait/core/tardis/control/impl/TelepathicControl.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/ThrottleControl.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/CrashableTardisTravel.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/TravelHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/TravelHandlerBase.java
You can now enqueue runnables to a tardis state
When the state changes, it runs all enqueued actions of the new state
eg - if you wanted to run something after the TARDIS next demats, youd enqueue to the FLIGHT state
I also fixed #1326 & #1325 as an example of how this system can be used.
Improvement of workflow, instead of adding things to `finishDemat` or similar you can simply enqueue to the returned `ActionQueue`
Hopefully this will also improve some peoples understanding of the codebase, as I've seen some people call things like
```
travel.demat
travel.crash
```
which wont work, as the TARDIS is still dematerialising and cannot crash in that state
`TravelHandler` now stores an `EnumMap` of `State`s and `ActionQueue`s 
`dematerialize` and related methods now return …
> Enqueue runnables to TARDIS states

- .github/workflows/version_sync.yml
Added a workflow which opens a PR main -> 1.3.0 on push to main
Ensures that the version branch is always up to date with the latest release.
> ci: open PR to merge main into ver on push

- src/main/java/dev/amble/ait/core/tardis/manager/old/DeprecatedServerTardisManager.java
This PR fixes an inconsistency in `ServerTardisManager` code that was there since beta of 1.1.0.
This fixes #1389 (or at least it should).
STM has a locking feature which prevents the STM from doing loading/saving/networking under certain circumstances. Previously, the STM wasn't being locked before server fully started.
**Changelog**
:cl:
- fix: no more seemingly random server crashes in multiplayer
> fix: lock STM on server start, add nullability check

- src/main/java/dev/amble/ait/core/tardis/ServerTardis.java
- src/main/java/dev/amble/ait/core/tardis/TardisDesktop.java
This PR fixes the addie bug.
Apparently, either something is querying tardis load on a non main-thread or something else is happening. Ideally, there should be a major TM refactor for async & lazy tardis loading as well lazy multidim loading in the future but for now this works.
**Changelog**
🆑
- fix: the addie bug is no more
> fix the addie bug

- src/main/java/dev/amble/ait/core/tardis/handler/ExtraHandler.java
- src/main/java/dev/amble/ait/data/properties/Value.java
This PR fixes the hammer crash. Previously, if you put the hammer in the slot it would crash dedicated servers.
Apparently, some silly goober didnt put the value load in the `#onLoaded` method. And some other silly guy made it so if the value isnt bound to any tardis then it's seen as if it was a client tardis. Obviously, the `syncToServer` doesn't exist on servers.
**Changelog**
🆑
- fix: the hammer no longer crashes dedicated servers
> fix the hammer crash

- src/main/java/dev/amble/ait/module/planet/core/PlanetBlocks.java
added @pickaxeminable tag to the oxygenator block
it was missing it, there for wouldnt drop on being broken, and took ages to drop
added `@PickaxeMineable(tool = PickaxeMineable.Tool.IRON)` to `PlanetBlocks` class
NA
- [x ] I have added media to this PR or it does not require an ingame showcase.
NA
**Changelog**
:cl:
- fix: oxygenator not droping on being mined
> fix: oxygenator now has pickaxeminable tag so will drop

- src/main/resources/data/ait/console/exile.json
- src/main/resources/data/ait/console/hartnell_mint_green_console.json
This PR adds the existing hartnell emissions-file to the two hartnell console variants "exile" and "mint green" (not to be confused with just the mint one).
All the hartnell variants have emissions except for the two that are loaded via JSON file (i.e. "exile" and "mint green"), which seems inconsistent, especially since the emissions light up the same elements for these two variants as for all the others.
I simply added the existing hartnell emissions file `hartnell_console_emission.png` to the two mentioned JSONs.
As a side-effect, this fix also prevents the exception `java.io.FileNotFoundException: ait:intentionally_empty` in the log when switching the console to one of these two JSON variants (due to the emissions-file now being referenced).
It also doesn't show the dark and purple …
> fix: two hartnell variants are missing emissions

- src/main/java/dev/amble/ait/client/models/consoles/HartnellConsoleModel.java
On the Hartnell console, when Hail Mary is off, its red indicator light is on (and vice versa).
It should be the other way around, so that the LED actually indicates the current state of the 813 protocol.
That is, if Hail Mary becomes active its LED should become active (and vice versa).
fixes #1445 
The alarms and door lock LEDs also function this way.
So for the sake of consistency if would make sense to have the hail mary / protocol 813 indicator behave the same way.
I simply inversed the condition that checks what state the hail mary indicator should be in.
**Changelog**
:cl:
- fix: Hail Mary LED was reversed on Hartnell consoles and now properly indicates protocol 813's status
> fix: hail mary indicator is reversed on hartnell consoles

- src/main/java/dev/amble/ait/core/tardis/TardisHandlersManager.java
- src/main/java/dev/amble/ait/data/enummap/ConcurrentEnumMap.java
- src/main/java/dev/amble/ait/data/enummap/EnumMap.java
This PR fixes a long standing bug in AIT (since, like, 1.0.4?). The bug that was randomly making handlers go null for no reason is now fixed!
The enum map used to store the handlers is using an array to store the handlers. Rarely, when the networking thread set the object but before it would put the new value in, the rendering thread would intervene and try to get the value, resulting in a null. This PR fixes it by using `synchronized` on a lock for array access.
**Changelog**
🆑
- fix: no more random crashes due to multithreading
> fix handlers being null sometimes due to multithreading

- src/main/java/dev/amble/ait/client/boti/TardisExteriorBOTI.java
When an exterior door is open during an alarm *and* there is no power, then the windows will be black, whereas all other windows are dark red.
This commit fixes it so that an exterior open door will show with the correct (dark red) color in the BOTI when alarms are on while the TARDIS is not powered.
It makes the exterior doors in the BOTI behave consistently with all the other windows.
I simply added another check to the existing ternary for the red color.
**Before:**
**After:**
**Changelog**
:cl:
- fix: exterior BOTI doors did not turn red during an alarm when power was off
> Exterior BOTI doors not turning dark red during alarm when TARDIS unpowered

- src/main/java/dev/amble/ait/mixin/client/experimental_screen/WorldOpenFlowsMixin.java
Currently when the "Show Experimental Warning" is set to "no", then the experimental-warning will only be disabled for the map _creation_ dialog. But it is also supposed to be disabled when opening existing maps, which it fails to do though.
This PR fixes this, so that the warning messages are not just disabled when creating a new map, but also when opening existing AIT maps.
Because it was supposed to work, as evidenced by the existence of the mixin made for that purpose ([WorldOpenFlowsMixin](https://github.com/amblelabs/ait/blob/main/src/main/java/dev/amble/ait/mixin/client/experimental_screen/WorldOpenFlowsMixin.java)).
If the `SHOW_EXPERIMENTAL_WARNING` setting is set to `false`, then the `confirmWorldCreation` method of the …
> Fix disabling of experimental message for map backup-prompt

- src/main/resources/data/ait/opinion/item/likes_pottery_shards.json
Removed "likes pottery shards"
Was invalid so air would be "correct" making it so you could easly get loyalty
I just removed pottery shards lol
**Changelog**
:cl:
- Removed pottery shards from opinions
> fix: removed "likes pottery shards"

- src/main/java/dev/amble/ait/mixin/client/experimental_screen/WorldOpenFlowsMixin.java
This reverts commit f4406a22539b127691dd94d31678b02d11c63525.
Apparently the previous PR works when testing via IDE, but the built JAR seems to fail the injection of the mixin.
Until I figure out a fix, this should probably be reverted.
Creates a crash on trying to load/create a map.
Produces this exception:
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method skipBackupScreen(Lnet/minecraft/class_437;Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in ait.mixins.json:client.experimental_screen.WorldOpenFlowsMixin from mod ait failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap ait-refmap.json
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject …
```
> Revert "fix disabling of map backup-prompt not working"

- src/main/java/dev/amble/ait/mixin/client/experimental_screen/WorldOpenFlowsMixin.java
Currently when the "Show Experimental Warning" is set to "no", then the experimental-warning will only be disabled for the map _creation_ dialog. But it is also supposed to be disabled when opening existing maps, which it fails to do though.
This PR fixes this, so that the warning messages are not just disabled when creating a new map, but also when opening existing AIT maps.
</BR>
**<ins>NOTE:</ins>** This is the second attempt of the PR.
The previous attempt (#1470) was rolled back (#1476) due to no mappings being generated for the JAR build.
But this time the mappings are implicity generated for the mixin (i.e. removed `remap = false`), not leading to a crash any longer. :)
Therefore, fixes #1477
Because it was supposed to work, as evidenced by the existence of the mixin made for that …
> Fix disabling of experimental message for map backup-prompt (take two)

- src/main/java/dev/amble/ait/core/item/sonic/TardisSonicMode.java
- src/main/java/dev/amble/ait/core/tardis/util/TardisUtil.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
- src/main/resources/assets/ait/lang/en_us.existing.json
This adds a max range of 256 blocks to the sonic summon.
@Ouroboros-Games menioned in Discord that this limitation was in before the sonic rewrite and it was meant to give the Stattenheim Remote more reason to exist.
I saw that the old sonic code used `isNearTardis()` and this method still exists in [ExteriorAnimation](https://github.com/amblelabs/ait/blob/main/src/main/java/dev/amble/ait/core/tardis/animation/ExteriorAnimation.java#L93).
But because that class is marked as deprecated, I copied its code (which is all self-contained) to the `TardisUtil` class and make use of it from there.
So in the `TardisSonicMode` class I simply add a `isNearTardis()` check as a guard clause to determine if the player is within 256 blocks of the TARDIS.
If they are, the code just continues as before.
If …
> Feat: Max range of 256 blocks for sonic summon

- src/main/java/dev/amble/ait/AITMod.java
- src/main/java/dev/amble/ait/core/commands/SetDoorParticleCommand.java
- src/main/java/dev/amble/ait/core/tardis/handler/DoorHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/InteriorChangingHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/TardisCrashHandler.java
- src/main/java/dev/amble/ait/core/tardis/util/TardisUtil.java
Particles spawn at the door after reconfig
Command to spawn them
closes #1458
Looks cool
`DoorHandler` holds `doorOpenParticle`
Every 5 ticks, if it isnt null and is open, it spawns these particles at the door
`InteriorChangingHandler` sets it to cloud
**Changelog**
:cl:
feat: after reconfig, steam particles spawn
feat: /ait door_particle command to spawn your own
> feat: spawning particles at door after reconfig

- src/main/java/dev/amble/ait/core/AITItems.java
- src/main/java/dev/amble/ait/core/item/SonicItem.java
- src/main/java/dev/amble/ait/core/item/sonic/OverloadSonicMode.java
- src/main/java/dev/amble/ait/core/item/sonic/SonicMode.java
- src/main/java/dev/amble/ait/datagen/datagen_providers/AITBlockTagProvider.java
feat(sonic): overload mode now costs 2x as much fuel fix(sonic): max stack is 1
Overload can now light obsidian on fire & costs 2x fuel
Fix sonic stacking above 1
closes #1073
closes #1180
see relevant issues
**Changelog**
:cl:
feat(sonic): overload can light nether portals
tweak(sonic): overload consumes 2x fuel
fix(sonic): stacking above 1
> Sonic Overload Changes

- src/main/java/dev/amble/ait/core/tardis/TardisHandlersManager.java
- src/main/java/dev/amble/ait/core/tardis/handler/SubSystemHandler.java
- src/main/java/dev/amble/ait/data/enummap/ConcurrentEnumMap.java
This is a follow up PR to my `EnumMap` thread safety fix.
The previous PR, while reducing the amount of race conditions, still
showed the buggy behavior of returning nulls.
Apparently, I've forgotten to override the get-by-index method.
**Changelog**
🆑
- fix: more stability
> EnumMap thread safety

- src/main/java/dev/amble/ait/core/item/sonic/InteractionSonicMode.java
- src/main/java/dev/amble/ait/core/item/sonic/OverloadSonicMode.java
- src/main/java/dev/amble/ait/core/item/sonic/ScanningSonicMode.java
- src/main/java/dev/amble/ait/core/item/sonic/TardisSonicMode.java
Currently the sonic modes are being executed twice in a row.
In scanning mode, it prints the message with the Artron levels of the rift chunk **two times**.
In Overcharge or Interact mode it's a bit difficult to stop at the desired state of the targeted block.
For example if you try to turn a redstone lamp *on*, then if you stop the sonic right when the lamp turns on, the lamp gets toggled once more and turns *off*.
This PR fixes this, so that each sonic's mode-function is not toggled twice in a row anymore.
Better UX.
(I.e. no doubling up of messages or an additional toggling after sonic use has already stopped.)
The reason for the double-call is because both the `startUsing` and `tick` methods are called when the sonic is used.
First `startUsing` gets called and processes the respective …
> fix sonic modes making double calls

- src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java
added the option to prank your friends by right clicking a slimeball on the control to lock it and shears to unlock it.
it makes it more interactive
**Changelog**
> Sticky keys

- src/main/java/dev/amble/ait/compat/gravity/GravityHandler.java
- src/main/java/dev/amble/ait/core/advancement/TardisCriterions.java
- src/main/java/dev/amble/ait/core/blocks/DoorBlock.java
- src/main/java/dev/amble/ait/core/item/InteriorTeleporterItem.java
- src/main/java/dev/amble/ait/core/tardis/ServerTardis.java
- src/main/java/dev/amble/ait/core/tardis/TardisDesktop.java
- src/main/java/dev/amble/ait/core/tardis/control/sequences/SequenceHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/ButlerHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/DoorHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/InteriorChangingHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/SiegeHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/SonicHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/WaypointHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/distress/DistressCall.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/CrashableTardisTravel.java
- src/main/java/dev/amble/ait/core/tardis/manager/old/DeprecatedServerTardisManager.java
- src/main/java/dev/amble/ait/core/tardis/util/TardisUtil.java
- src/main/java/dev/amble/ait/core/util/Lazy.java
- src/main/java/dev/amble/ait/core/world/TardisServerWorld.java
- src/main/java/dev/amble/ait/registry/impl/SequenceRegistry.java
This PR adds lazy tardis ticking.
Previously, the tardises would tick in any condition, even if they are not loaded outside or inside. Now they don't!
Besides that, the PR fixes AIT to lazily load the world instead of getting it loaded right away. Unfortunately, as of the currently used version of multidim this won't actually guarantee lazy world loading.
- `TardisDesktop#getInteriorWorld` -> `TardisDesktop#worldRef`
**Changelog**
:cl:
- perf: improved ticking large amounts of tardises
> Lazy tardis ticking

- src/main/java/dev/amble/ait/AITMod.java
- src/main/java/dev/amble/ait/core/AITTags.java
- src/main/java/dev/amble/ait/core/item/sonic/ScanningSonicMode.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
- src/main/java/dev/amble/ait/datagen/datagen_providers/AITBlockTagProvider.java
- src/main/java/dev/amble/ait/mixin/server/BellBlockMixin.java
- src/main/resources/ait.mixins.json
This PR adds a TARDIS locator ability to the sonic scanning mode.
When in scanning mode, interacting (right-clicking) on any Zeiton block will display the linked TARDIS' coordinates.
The Zeiton block requirement is to balance it a bit. The in-world idea is:
The sonic needs to interact with some Zeiton to make it resonate at the linked TARDIS' frequency, which sends a pulse through space-time that gets reflected by the linked TARDIS, kind of like space-time sonar.
Not sure if that is a satisfying explanation, but if you want other blocks as a requirement or don't want the block limitation at all, let me know. :)
It provides yet another alternative to get back to one's TARDIS, next to the Stattenheim Remote and the Hazandra.
The former gets the TARDIS to the player, if there's enough fuel. …
> Add TARDIS locator functionality to sonic scanning mode

- src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java
- src/main/java/dev/amble/ait/core/tardis/control/Control.java
This PR fixes control entity interactions from multiple PRs.
Because controls are unusable otherwise lol.
Previously, it seems that hammer check would bypass the durability check. Also, the durability check would always return a true/false value even if the random check fails. E.g. if the control is slightly broken, it would return before executing the control's method.
**Changelog**
:cl:
- fix: hammer no longer bypasses durability check
- fix: control entities can be interacted with again
- fix: you can interact with slightly broken controls again
> fix: control entity interactions

- src/main/java/dev/amble/ait/client/AITModClient.java
- src/main/java/dev/amble/ait/client/boti/BOTI.java
- src/main/java/dev/amble/ait/client/renderers/entities/BOTIPaintingEntityRenderer.java
- src/main/java/dev/amble/ait/client/renderers/entities/GallifreyanPaintingEntityRenderer.java
- src/main/java/dev/amble/ait/client/renderers/entities/TrenzalorePaintingEntityRenderer.java
Fixes Gallifrey Falls deciding it wants to transition to Trenzalore.
We're clearly transpaintingphobic here at AIT Incorporated.
Separate the Trenzalore and Gallifrey Falls paintings so no more transpainting can occur.
**Changelog**
> Gallifrey Falls Keeps Turning Into Trenzalore, BUT NO MORE I SAY

- src/main/java/dev/amble/ait/AITMod.java
- src/main/java/dev/amble/ait/core/tardis/util/AsyncLocatorUtil.java
This PR makes it so the executor service for the async locator util is re-initialized on server startup.
Fixes a bug in singleplayer that occurs when a player leaves a world and rejoins again and uses something that utilizes the async locator util (e.g. randomizer or the thingy that searches for structures).
**Changelog**
:cl:
- fix: randomizer and structure locator no longer throw up when you rejoin the world
> re-initialize the executor service on server startup

- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
changed `LINK TO ENGINE VIA FLUID LINKS`
It was wrong
changed `LINK TO ENGINE VIA FLUID LINKS` to `changed `LINK TO ENGINE VIA ARTRON CABLES` in the `AITModDataGenerator` class
NA
NON
**Changelog**
:cl:
- fix: "LINK TO ENGINE VIA FLUID LINKS" being wrong name for artron cables
> fix: "LINK TO ENGINE VIA FLUID LINKS" being wrong name for artron cables

- src/main/java/dev/amble/ait/core/world/TardisServerWorld.java
This PR makes it so tardis worlds tick with the tardises they are linked to.
For performance, of course!
This PR utilizes the `ServerTardis#shouldTick` method, which was implemented in #1509.
**Changelog**
:cl:
- fix: tardis' interior no longer ticks if no one is inside or outside (or if the tardis' interior chunks aren't loaded).
> make tardis worlds tick lazily

- src/main/java/dev/amble/ait/api/tardis/link/LinkableItem.java
- src/main/java/dev/amble/ait/api/tardis/link/v2/TardisRef.java
- src/main/java/dev/amble/ait/client/tardis/manager/ClientTardisManager.java
- src/main/java/dev/amble/ait/client/util/ClientTardisUtil.java
- src/main/java/dev/amble/ait/core/tardis/TardisManager.java
- src/main/java/dev/amble/ait/core/tardis/manager/TardisFileManager.java
- src/main/java/dev/amble/ait/core/tardis/manager/old/DeprecatedServerTardisManager.java
- src/main/java/dev/amble/ait/data/TardisMap.java
This PR makes it so if a tardis was not serialized properly and saved a corrupted file it won't brick your world anymore.
This happened on the official server. Not cool.
- Everything that uses `TardisManager`s has to provide non-null values.
**Changelog**
:cl:
- fix: if a tardis fails to save it wont brick your world anymore
> no more empty saves

- build.gradle
- src/main/java/dev/amble/ait/core/tardis/TardisDesktop.java
- src/main/java/dev/amble/ait/core/tardis/manager/old/DeprecatedServerTardisManager.java
- src/main/java/dev/amble/ait/core/world/TardisServerWorld.java
- src/main/java/dev/amble/ait/mixin/server/multidim/MultiDimLoadFix.java
This is another performance PR with general performance fixes.
Because the performance SUCKS.
This PR makes it so the doors don't close on world save. I dont know why this was even a thing. Next, players are now restricted in block placement. They can only place blocks in the 500 block radius from the center of the world (x: 0, z: 0). 
Also this PR forces the server tardis manager to save the tardises only when the overworld gets saved (and not the other 100 miniworlds).
**Changelog**
:cl:
- perf: general performance improvements
> Various perf fixes

- src/main/java/dev/amble/ait/core/world/TardisServerWorld.java
This PR reverts world border restrictions of the #1548 and adds biome caching to the tardis world.
A bunch of people came with pitchforks and torches.
Biome caching is done through lazy initialization.
**Changelog**
:cl:
- tweak: slightly improved biome check of the tardis world
> revert world border restrictions & add biome caching

- src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java
- src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java
- src/main/java/dev/amble/ait/core/tardis/control/Control.java
This PR prevents interact-ability of the console controls during a TARDIS' growth-state.
fixes #1525 
The console controls should not be interactable during growth mode, as the TARDIS has not yet fully formed.
There is a guard-clause early on in the control-code, which returns false if the TARDIS is in the growth-state (so that neither the sound for a control plays, nor a missing-subsystem message is displayed, etc.).
**Changelog**
:cl:
- fix: controls were interact-able during growth state, but shouldn't
> Fix some controls being interact-able during growth state

- src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java
This PR fixes the sticky-controls feature (#1503) being bypassed when punching (i.e. left-clicking) controls.
When controls are being made sticky, then it shouldn't matter if we left- or right-click them.
They should prevent the control from operating in either case.
(The mentioned methods all relate to [ConsoleControlEntity](https://github.com/amblelabs/ait/blob/main/src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java))
When interacting (i.e. right-clicking) with a control, the `interact` method is called, at the end of which the `run` method is called (which executes the main functionality of the control).
The `interact` method handles sticky controls and prevents `run` from being called.
But when punching (i.e. left-clicking) a sticky control, this calls `run` directly …
> fix sticky controls being bypass-able via left-click

- src/main/java/dev/amble/ait/core/blockentities/ExteriorBlockEntity.java
- src/main/java/dev/amble/ait/core/item/SiegeTardisItem.java
- src/main/java/dev/amble/ait/core/tardis/handler/SiegeHandler.java
This PR fixes the backwards compatibility between the new and one of the older releases.
One of the previous PRs allowed to use `null` values in properties. This PR fixes the backwards compatibility of the TARDIS' created before that release.
`SiegeHandler` was changed to use the null value to check whether the sieged tardis is being held or not, but the older versions used `new UUID(0, 0)`.
**Changelog**
🆑
- fix: siege should be held-able with TARDIS' created prior to one of the previous releases
> fix: siege held uuid backwards compat

- src/main/java/dev/amble/ait/client/boti/TardisDoorBOTI.java
- src/main/java/dev/amble/ait/client/renderers/exteriors/ExteriorRenderer.java
- src/main/java/dev/amble/ait/client/util/ClientTardisUtil.java
- src/main/java/dev/amble/ait/client/util/FoggyUtils.java
This PR makes it so the emission layer doesn't render for no power and no alarm exterior.
Because some no power exteriors look weird now.
Basically, the code was tinting the emission layer near-black color instead of just not rendering the emission layer. A lot of exteriors depended on that behavior so they started to look really weird after this change.
**Changelog**
🆑
- fix: render unpowered exterior emission properly
> fix: dont render emission if there's no power power and no alarms

- src/main/java/dev/amble/ait/client/renderers/entities/RiftEntityRenderer.java
Rifts now render as purple lines when BOTI is off.
They can actually see them now.
Just made the BOTI queue get added to when its enabled, otherwise render static rift model.
**Changelog**
:cl:
- fix: rifts now render when BOTI is off.
> Rifts Are Now VISIBLE With BOTI Off

- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
- src/main/java/dev/amble/ait/datagen/datagen_providers/AITRecipeProvider.java
- src/main/java/dev/amble/ait/module/planet/PlanetModule.java
added recipes to all the planet blocks
because someone thought it would of been a good idea to not add any recipes when they made these
closes #1664 
added identifiers to smelting and blasting recipes
https://github.com/user-attachments/assets/9acdf738-2cba-431b-86ea-fef273d18b1d
> Planet block recipes

- src/main/java/dev/amble/ait/core/tardis/handler/travel/TravelUtil.java
This PR changes the randomizer to choose coordinates relative to the TARDIS' current position.
Before it was only choosing coordinates relative to spawn.
Closes #1693
It has been confirmed by @DrTheodor to be an oopsie during one of the travel rewrites.
I simply added the TARDIS' current X and Z coordinates to the increment values.
**Changelog**
:cl:
- fix: Randomizer now chooses coordinates relative to the TARDIS' position
> Fix randomizer only choosing coordinates around spawn

- src/main/java/dev/amble/ait/client/models/consoles/AlnicoConsoleModel.java
- src/main/java/dev/amble/ait/client/models/consoles/CopperConsoleModel.java
- src/main/java/dev/amble/ait/client/models/consoles/CoralConsoleModel.java
- src/main/java/dev/amble/ait/client/models/consoles/CrystallineConsoleModel.java
- src/main/java/dev/amble/ait/client/models/consoles/RenaissanceConsoleModel.java
- src/main/java/dev/amble/ait/client/models/consoles/ToyotaConsoleModel.java
On consoles monitorss, the destination display shows travel progress just like the current position display does.
This behaves differently to the CRT monitor, wall-monitor and the internal monitor of the console, as the destination display 
on those remains fixed during flight.
This PR fixes that, so that the display of the destination coordinates on consoles with two monitors isn't lost during flight.
(Monitors with current-position will already show travel progress anyways.)
It also fixes the red cross and blue icons on the console monitors to indicate the correct position (current vs destination), to bring them in line with the CRT monitor, wall-monitor and the internal monitor of the consoles.
<details>
<summary>Click me for detailed comparison</summary>
**<ins>Before - when …
> fix progress display on console monitors

- src/main/java/dev/amble/ait/core/tardis/handler/FuelHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/ProgressiveTravelHandler.java
- src/main/java/dev/amble/ait/core/tardis/util/TardisUtil.java
This PR adjusts the travel and fuel formulas to be more consistent and less buggy.
Previous (2 y/o) formulas used XOR instead of using power (which was certainly NOT a feature), resulting in higher speeds consuming less fuel than they should. Travel didn't consider instability as travel speed boost.
The new formulas are now linear. The travel formula now adds the `instability - 1` to flight ticks (per flight tick, ofc).
None
**Changelog**
🆑
- fix: hammer now boosts travel speed again
- fix: flying on max speed doesn't drain your tardis to 0 artron
> fix: adjusted the fuel and travel tick formulas

- src/main/java/dev/amble/ait/module/planet/PlanetModule.java
fixed stonecutting
anorthosite bricks would make martian bricks in the stonecutting
**Changelog**
:cl:
+ fix anorthosite stonecutting
> fix: stonecutting anorthosite bricks

- src/main/java/dev/amble/ait/client/config/AITClientConfig.java
- src/main/java/dev/amble/ait/client/renderers/consoles/ConsoleRenderer.java
- src/main/java/dev/amble/ait/client/renderers/monitors/MonitorRenderer.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
This PR adds a client config option to toggle the text display on CRT and console-monitors on/off. (default: on)
Closes #1700
So that people can use it for different RP scenarios, or they just prefer the monitors for decorative purposes, etc.
</br>
</br>
<details>
<summary><ins>Another example</ins></summary>
</details>
**Changelog**
:cl:
- add: Client option to toggle CRT- and console-monitor text on/off
> Feature: Client config option to toggle CRT- and console-monitor text on/off

- src/main/java/dev/amble/ait/client/util/ClientTardisUtil.java
This PR fixes extreme shaking as seen in #1755. Fixes #1755.
Because such screen shaking makes the game unplayable.
Shaking intensity during flight depends on the distance from the console. If there's no console then the method `getDistanceToConsole` will return `Double.MAX_VALUE`, which somewhat makes sense logically, but breaks the logic. This PR updates this method to return 0 in case there are no consoles.
Although returning 0 doesn't make sense logically, this method returns 0 if it encounters an error (like, if the client player is not in a tardis, or, if theres, for some reason, the lack of the tardis object).
- `ClientTardisUtil#distanceFromConsole` does no longer return `Double.MAX_VALUE` if there are no consoles.
**Changelog**
:cl:
- fix: no more extreme screen shaking when …
> fix: extreme shaking

- src/main/java/dev/amble/ait/core/item/sonic/TardisSonicMode.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
if the tardis has no power and you try and summon it, it will now send a message to the player saying the power is off
**Changelog**
:cl:
- add sonic screwdriver summon notify if no power
> sonic screwdriver summon notify if no power

- src/main/java/dev/amble/ait/core/tardis/handler/FuelHandler.java
The axe breaking powered down locked TARDIS code.
It will make wooden and stone axes not able to break down the doors making it more of a challenge and Theo told me to impliment it.
if (stack.getItem() instanceof AxeItem axeItem && axeItem.getAttackDamage()>=8 && stack.getItem() != Items.STONE_AXE) {
- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://amblelabs.github.io/ait-wiki/guidelines).
- [X ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
<!--
:cl:
- remove: wooden and stone axes being able to break open TARDIS doors.
- add: iron and upwards being able to break TARDIS doors open + mod compatability too.
> Added the Axe thing Theo told me also made it mod compatible

- src/main/java/dev/amble/ait/core/tardis/Tardis.java
This PR makes the already available growth desktop to be used without borking your TARDIS.
It's a pretty nice interior and people have tried to use it only to bork their TARDIS.
"Is TARDIS in growth?" check checks whether the exterior is a TARDIS coral OR the interior is the cave interior. This PR removes the second condition.
**Changelog**
:cl:
- fix: TARDIS' no longer break when using the default cave interior
> Allow the use of default cave interior without breaking growth checks

- src/main/java/dev/amble/ait/core/blockentities/ExteriorBlockEntity.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
When a player attempts to enter a growth TARDIS during its initial interior reconfiguration, this PR will display an action-bar message informing the player about the ongoing progress.
For some players it can take a while for the groth interior to reconfigure.
So to prevent players from being confused as to what's going on, displaying a message when they try to enter the TARDIS (during the growth reconfiguration) will help with that.
A condition at the end of the exterior's collision method checks if the door is closed, a player tries to enter and if we currently have a growth TARDIS.
If so, a translatable message (in red) is displayed to the player in the action-bar.
https://github.com/user-attachments/assets/50a04707-9146-4063-93fa-6e9894abe4bc
**Changelog**
:cl:
- add: action-bar …
> Inform player if growth is still in progress

- src/main/java/dev/amble/ait/core/item/sonic/InteractionSonicMode.java
- src/main/java/dev/amble/ait/core/item/sonic/OverloadSonicMode.java
- src/main/java/dev/amble/ait/core/item/sonic/SonicMode.java
- src/main/java/dev/amble/ait/datagen/datagen_providers/AITBlockTagProvider.java
This PR adds the ability to toggle a lever via the sonic's _overload_ mode
and the ability to press a stone button via the sonic's _interaction_ mode.
It was asked for in here: https://discord.com/channels/1213989169878274068/1402420014350598255
And Saturn was already researching it.
The existing `getHitResult` was insufficient, because it relied on `ProjectileUtil.getCollision`, which only does a raycast that detects blocks it *collides* with.
Since levers and buttons don't have collision, that wouldn't work to detect them.
So I had to add a new method to `SonicMode` called `getHitResultForOutline` that creates a raycast that detects the *outline* of a block instead.
https://github.com/user-attachments/assets/2a8c30f7-f5d3-4899-bcce-f765fbf9c4d1
**Changelog**
:cl:
- add: Sonic Overload …
> Feat: sonic lever and button interaction

- src/main/java/dev/amble/ait/core/item/sonic/OverloadSonicMode.java
This PR fixes the sonic overload mode not breaking all glass.
Because it should break all glass equally.
Replaced the condition checks to more generic glass/glass-pane classes.
**Changelog**
:cl:
- fix: overload did not break all glass and glass panes
> fix overload not breaking all glass and glass panes

- src/main/java/dev/amble/ait/core/blocks/FoodMachineBlock.java
fix: fixed the aitsound load_waypoint
fix bugs
the food machine couldnt be mined with an iron pick and the sound id was invalid
:cl:
- fix: food machine
> fix: food machine can be mined with iron pick and sound fix

- src/main/java/dev/amble/ait/core/item/sonic/OverloadSonicMode.java
I added a feature to the overload mode so that it will break bricks
https://discord.com/channels/1213989169878274068/1213989171241426954/1402985541766615082
fuck off and die
:cl:
- feat: overload mode breaks bricks
> feat: overload mode breaks bricks now

- .github/workflows/publish-devbuilds.yml
- gradle.properties
- src/main/java/dev/amble/ait/core/blocks/ConsoleGeneratorBlock.java
Makes punching (left-clicking) the console generator in creative mode not break it but browse to the previous console.
Breaking the console generator in creative mode (while inside the TARDIS) now only happens when punching it while holding any item in the main hand.
And then it will drop the console generator item, just like when breaking it outside of the TARDIS.
To make it consistent with the behavior in survival.
This also prevents accidental breaking while in creative mode.
This PR relies on https://github.com/amblelabs/modkit/pull/35 and uses that to detect whether the player who attempted to break the console generator is sneaking or not.
This information is used to enable the browsing to the *previous* console/variant while in creative mode (see `onTryBreak`).
(Browsing to the …
> fix console generator breaking in creative mode

- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
Fix spelling of spelling fix.
The spelling was not fully fixed.
I added an apostrophe.
**Changelog**
:cl:
- fix: description.attack_eyebrows spelling, for real this time
> fix: description.attack_eyebrows spelling again

- src/main/java/dev/amble/ait/api/tardis/TardisEvents.java
- src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java
- src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java
- src/main/java/dev/amble/ait/core/tardis/control/Control.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/ElectricalDischargeControl.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/EngineOverloadControl.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/PowerControl.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/RandomiserControl.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/SecurityControl.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/SiegeModeControl.java
- src/main/java/dev/amble/ait/core/tardis/control/impl/TelepathicControl.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/TravelHandler.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
This PR adds an arming mechanism to the engine overdrive.
First press arms it.
Pressing again within 5 seconds executes overdrive.
Pressing any other control or waiting 5 seconds disarms it.
The 5 minute cooldown only starts after overdrive was executed.
To prevent accidental activation.
I added two static functions to the engine overdrive control that arm and disarm it:
`arm()` sets a boolean to true and starts a confirmation-timer that will disarm the overdrive after 5 seconds (20 * 5 ticks).
`disarm()` sets the same boolean to false and cancels the confirmation-timer.
When the control is first pressed, overdrive will be armed and return.
If the control is pressed again within the confirmation-time, overdrive is disarmed (just to reset the state) and the dumping of Artron is allowed to …
> Feat: Add engine overdrive arming mechanism

- src/main/java/dev/amble/ait/client/config/AITClientConfig.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
- src/main/java/dev/amble/ait/module/planet/client/SpaceSuitOverlay.java
- src/main/java/dev/amble/ait/module/planet/core/space/planet/Planet.java
- src/main/resources/assets/ait/lang/uk_ua.existing.json
Makes the space suit display Celsius degrees when Celsius setting is chosen instead of displaying Fahrenheit degrees.
Also fixes some Celsius spelling and improves the temperature config enum code.
Because Celsius is not Fahrenheit.
Changed a call to `celsius()` instead of `fahrenheit()` where Celsius was called for (pun intended).
**Changelog**
:cl:
- fix: Celsius was showing Fahrenheit degrees
> Fix celsius showing fahrenheit degrees

- src/main/java/dev/amble/ait/core/item/KeyItem.java
When Hail Mary protocol is active and the conditions for it trigger when the player is inside a TARDIS, then it currently makes the player's TARDIS land inside the TARDIS ((be that itself or another).
This PR fixes that.
TARDISes are (currently) not meant to travel into TARDISes.
I added a simple `isTardisDimension` check for when the Hail Mary protocol fires, similar to how it's already done with the `TARDIS` mode of the sonice screwdriver.
**Changelog**
:cl:
- fix: TARDIS in TARDIS landing was still possible via Hail Mary protocol.
> Prevent TARDIS in TARDIS landing via Hail Mary protocol

- src/main/java/dev/amble/ait/client/screens/MonitorScreen.java
Exclusives are now only shown if unlocked for a player UUID.
And the Coral Growth exterior is back to being skipped again.
(I'm not going to mention the crystal growth bulletpoint in the changelog, as that was a regression introduced after the latest release, so it wouldn't be a fix since then).
The coral growth exterior shouldn't appear at all and the exclusives should be exclusive.
Checking via `instanceof` didn't seem to work, so I instead did an `.equals` check against the respective categories.
**Changelog**
:cl:
- fix: Exclusive exteriors are now exclusive again
> fix exterior selection screen

- src/main/java/dev/amble/ait/mixin/server/ItemEntityMixin.java
When items are dropped inside the TARDIS, they instantly get teleported to the door.
They should only get teleported to the door if they fall below the bottom Y of the dimension.
I simply removed a negative sign that was probably carry-over from the `ServerPlayerMixin`, where the Y coordinate for teleporting players was `-100`.
But in the `ItemEntityMixin` it references `entity.getWorld().getBottomY()`, which is *already* negative (-64 to be precise).
So having a negative sign in front of that would check against `64`, which is *not* the bottom Y of the dimension, but way above the console room.
**Changelog**
:cl:
- fix: Dropped items in interior were being teleported instantly
> fix dropped items in interior being teleported instantly

- src/main/java/dev/amble/ait/core/blocks/PeanutBlock.java
- src/main/java/dev/amble/ait/core/entities/FallingTardisEntity.java
- src/main/java/dev/amble/ait/core/item/HammerItem.java
- src/main/java/dev/amble/ait/core/tardis/handler/SelfDestructHandler.java
- src/main/java/dev/amble/ait/core/tardis/handler/travel/CrashableTardisTravel.java
- src/main/java/dev/amble/ait/core/tardis/util/TardisUtil.java
Fixes the gamerules `tardisGriefing` and `tardisFireGriefing`.
If `tardisGriefing` is set to `true`, then explosions will destroy blocks, otherwise not.
If `tardisFireGriefing` is set to `true`, then explosions will also create fire (only if `tardisGriefing` is also true), otherwise not.
The gamerules were only doing something effective for a crashing TARDIS that was falling.
No other explosions (of *any* fires) were controlled by them.
I extracted the `ExplosionBehavior` from `FallingTardisEntity` and put it in `TardisUtil` so it can be used from one central location.
Then I added this ExplosionBEhavior to all other explosions.
Additionally I added a `doCreateFire` method to `TardisUtil` that checks the gamerule `tardisFireGriefing` and added a call to it to all the explosions as well. …
> Fix explosion (and fire) gamerules

- src/main/java/dev/amble/ait/AITMod.java
Do not show the experimental release warning (the red writing at the top in the main menu) for release versions.
It's only supposed to be shown for non-release versions (testbuilds, betas, etc.).
Previously, the mod tested if the branch part of the string *equals* `"release"`, but the release version string ends with `"release+mc.1.20.1"` which is not equal to `"release"`.
To fix this I did two things:
- determine the branch name not just by looking at everything after the first "-", but also stop before the first "+".  
So for `"ait-1.2.12-release+mc.1.20.1"` it would return `"release"`.
- Change the check from an `equals` to a `contains`, to make it more robust if other changes happen to the string in the future.  
Because I assume if the version string contains `"release"` anywhere, …
> Fix the experimental warning being shown for release versions

- src/main/java/dev/amble/ait/core/drinks/DrinkUtil.java
- src/main/java/dev/amble/ait/core/item/DrinkItem.java
This PR fixes the drink client crash.
_Someone_ forgot a null check for the drink, resulting in the rendering code trying to get a color of a non existent drink.
**Changelog**
:cl:
- fix: drinks no longer crash people
- fix: you cant drink air anymore
> fix drink client crash

- src/main/java/dev/amble/ait/client/models/exteriors/BookshelfExteriorModel.java
Fixes the bookshelf BOTI for the exterior.
Because it was rotated so that opening the left door showed the BOTI's right door opening and vice versa.
I rotated it by 180 degrees and moved it into the right place to fit snugly with the exterior doors.
https://github.com/user-attachments/assets/76f37be5-9585-446e-b4c1-b6130b3a97b6
**Changelog**
:cl:
- fix: Bookshelf exterior BOTI showed the doors rotated by 180 degrees and floating.
> fix bookshelf exterior BOTI

- src/main/java/dev/amble/ait/core/commands/ThisTardisCommand.java
- src/main/java/dev/amble/ait/datagen/AITModDataGenerator.java
Adds a fail message for the `this` command.
When the player is ...
... not in a TARDIS
... and doesn't hold a linkable item or the linkable item is not linked
then an informative message is displayed.
Previously it just didn't output anything under the mentioned conditions.
For better UX an informative message makes sense.
There's not much to it, I added a message (via a translatable string).
**Changelog**
:cl:
- add: Fail notification for `/ait this` command
> add fail notification for '/ait this' command

- src/main/java/dev/amble/ait/core/AITBlocks.java
if you dont know why i removed it its the same issue that aitextras has with all of its blocks
removed `.nonOpaque` from most ait blocks that should cull when surrounded by blocks
blocks that don't need to will now cull properly when surrounded by blocks
removed  `.nonOpaque`  block properties in the `AITBlocks` class
NA
NON
**Changelog**
:cl:
- fix: removed .nonopaque property from blocks that dont need it
> fix: removed .nonopaque property from blocks that dont need it

- src/main/java/dev/amble/ait/mixin/server/ServerPlayerMixin.java
When leave-behind is enabled and a player falls into the TARDIS void, then without a key (and valid loyalty level) they will be spawned outside the TARDIS instead of at the interior door.
This was a a suggested idea on Discord by `ihudhudi` here:
https://discord.com/channels/1213989169878274068/1420864949474951189/1420864949474951189
Added an additional check to the existing ServerPlayerMixin to check for a matching key and the leave-behind setting.
**Changelog**
:cl:
- add: When leave-behind is on, then players falling into the TARDIS void without a key (and valid loyalty level) will be evicted from the TARDIS.
> Feat: Evict players who fall into void without a key when leave-behind is on
